[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
verbosity = 2

[rpc_endpoints]
local = "http://localhost:8545"
upside = "https://${UPSIDE_RPC_URL}"

# https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
# https://book.getfoundry.sh/config/
# https://github.com/juanfranblanco/vscode-solidity?tab=readme-ov-file
